name: Compress images
on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
          
  wip:
    name: "Set status"
    runs-on: ubuntu-latest
    steps:
      - uses: wip/action@master
